Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,7 @@ jobs:
 
       - name: Write and format the JSON secret to a file
         run: |
-          printf "%s" "${{ secrets.JSON_FILE_CONTENT }}" | jq '.' > nebula-dev5.json || { echo "Failed to format JSON"; exit 1; }
+          printf "%s" "${{ secrets.GCP_CREDENTIALS }}" | jq '.' > nebula-dev5.json || { echo "Failed to format JSON"; exit 1; }
 
       - name: Display the file content (for debugging purposes)
         run: cat nebula-dev5.json
